### ISSUE TITLE
cuda verison

### ISSUE THREAD

**Issue by JamesZWalker** [ml-research/rational_activations#16]
Is cuda9.2 OK?

**Comment by k4ntz** [comment]
Hi ! 
I just created an installable wheel normally compatible with any cuda and any platform. 
I created the branch old_cuda (that will be renamed soon).
To install:

- `pip3 install -U pip wheel`
- `wget https://github.com/ml-research/rational_activations/blob/old-cuda/anywheel/rational_activations-0.1.1-py3-none-any.whl\?raw\=true -O rational_activations-0.1.1-py3-none-any.whl`
- `pip3 install rational_activations-0.1.1-py3-none-any.whl`

You have to use python >= 3.6 as we use f-string in the source code.

let me know how that works, I close for now :)

**Comment by k4ntz** [comment]
Please re-open if any related problem
