### ISSUE TITLE
TypeError when initializing a rational activation function in Keras

### ISSUE THREAD

**Issue by McLovin90** [ml-research/rational_activations#18]
Hi,

when initializing a rational activation function in Keras as described in the README file, I receive the following error:

`TypeError: __init__() missing 1 required positional argument: 'name'`

This error leads to line 60 of the file rational_base.py, whose ` __init()` method expects an additional argument, which is never provided in the inheriting class Rational(). However, when adding an argument to `super().__init(name)` in the rational.py file, I receive another error:

`AttributeError: Can't set the attribute "name", likely because it conflicts with an existing read-only @property of the object. Please choose a different name.`

I don't know how to to fix it yet. Interestingly, when using pytorch, everything just works fine. Maybe you guys can help me.

**Comment by k4ntz** [comment]
Hi ! Thank you for your report ! 
I have modified the TF/Keras and MXNet Rationals, could you try pull, install (or develop), try again and let me know, I am now able to use it, if so, I'll recompile it and push on pypi.

**Comment by McLovin90** [comment]
Everything works fine. Thanks

**Comment by k4ntz** [comment]
Thanks, I close it.
