### ISSUE TITLE
setup.py returns TypeError: module() takes at most 2 arguments (3 given)

### ISSUE THREAD

**Issue by McLovin90** [ml-research/rational_activations#19]
Hi,

when running the command

`python3 setup.py install --user`,

I receive the error described above at line 137 in the setup.py file. I wasn't able to fix this problem on my own. Maybe you guys can help me out.

**Comment by k4ntz** [comment]
Hey I don't see the description of your error, could you paste it here please ?

**Comment by McLovin90** [comment]
``
Traceback (most recent call last):
  File "setup.py", line 138, in <module>
    class clean_all(clean):
TypeError: module() takes at most 2 arguments (3 given)
``

**Comment by k4ntz** [comment]
What python version are you using? 
For me, `clean` imported by line 4 (`from distutils.command.clean import clean`) is a class, so I don't get this error.

**Comment by McLovin90** [comment]
Python 3.8.5

**Comment by k4ntz** [comment]
Otherwise you could replace the `clean_all` class by :
```
class clean_all():
    def run(self):
        pass
``` 
As clean is anyhow not called by `setup.py install`

**Comment by McLovin90** [comment]
Replacing the clean_all method just worked fine. Thanks for the fast reply. BTW I didn't know that it is possible to install the package from PyCharm.

**Comment by k4ntz** [comment]
Top ! No problem ! I close the issue then :)
