### ISSUE TITLE
Encoding issue file read

### ISSUE THREAD

**Issue by PaVim96** [ml-research/rational_activations#7]
The following code will result in an ascii encoding error when trying to execute in container:
https://github.com/ml-research/rational_activations/blob/8efb850a49f5feaea669794aa9ef977fed8b7df5/setup.py#L115-L119

**Comment by PaVim96** [comment]
Suggestion: 
adding the following file opening code for a file should fix the issue when in a container:
`with open(FILENAME, "rb") as fh:`

**Comment by k4ntz** [comment]
One could also just assign empty string to the variables:
`long_description = ""`
and
`requirements = fh.readlines()`
and then `pip3 install -r requirements.txt`

Thanks for the feedback, I am closing

**Comment by k4ntz** [comment]
One could also just assign empty string to the variables:
`long_description = ""`
and
`requirements = fh.readlines()`
and then `pip3 install -r requirements.txt`

Thanks for the feedback, I am closing
